CREATE TABLE Benutzer (email VARCHAR(50) NOT NULL, passwort VARCHAR(50) NOT NULL, vorname VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, strasse VARCHAR(50) NOT NULL, ort VARCHAR(50) NOT NULL, postleitzahl INTEGER NOT NULL, telefonnummer BIGINT NOT NULL ,land VARCHAR(50) NOT NULL,PRIMARY KEY(email))


CREATE TABLE Flughafen( code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, stadt VARCHAR(50) NOT NULL, land VARCHAR(50) NOT NULL, PRIMARY KEY(code) )

CREATE TABLE Flugzeug(modell VARCHAR(50) NOT NULL, PRIMARY KEY(modell))

CREATE TABLE Flug(nummer VARCHAR(50) NOT NULL, von VARCHAR(50) NOT NULL, nach VARCHAR(50) NOT NULL, abflugzeit TIME NOT NULL, ankunftzeit TIME NOT NULL, dauer TIME NOT NULL, businesspreis INT NOT NULL, economypreis INT NOT NULL, geplant VARCHAR(50) NOT NULL, flugzeug VARCHAR(50) NOT NULL, PRIMARY KEY(nummer), FOREIGN KEY(flugzeug) REFERENCES Flugzeug, FOREIGN KEY(von) REFERENCES Flughafen, FOREIGN KEY(nach) REFERENCES Flughafen)

CREATE TABLE Ticket (id	INTEGER NOT NULL, abflugdatum  DATE NOT NULL, sitzreihe INTEGER NOT NULL, sitzspalte INTEGER NOT NULL, klasse VARCHAR(50) NOT NULL, flug VARCHAR(50) NOT NULL, benutzer VARCHAR(50) NOT NULL, PRIMARY KEY(id), FOREIGN KEY(benutzer) REFERENCES Benutzer, FOREIGN KEY(flug) REFERENCES Flug )

